export const ACTION_TYPE = {
  GET_DATA: 'GET_DATA',
  SEARCH_PRODUCT: 'SEARCH_PRODUCT',
  FETCH_ALL_PRODUCTS: 'FETCH_ALL_PRODUCTS',
  UPLOAD_PRODUCT: 'UPLOAD_PRODUCT',
  UPLOAD_PRODUCTS_STATUS: 'UPLOAD_PRODUCTS_STATUS',
  DASHBOARD_SELECTED_PRODUCTS: 'DASHBOARD_SELECTED_PRODUCTS',
  SHOW_EDIT_POPUP: 'SHOW_EDIT_POPUP',
};
